datacarpentry/astronomy-python

_config.yml
- set overall lesson title (open to suggestions on making this better!)
- set life-cycle stage to beta
- set carpentries to "dc" for Data Carpentry
=> set lesson variables

_episodes/01-query.md, _episodes/02-coords.md, _episodes/03-motion.md, _episodes/04-select.md, _episodes/05-join.md, _episodes/06-photo.md, _episodes/07-plot.md
Based on timings from January pilot. Total instructional time = 9.5 hours.
=> Add timings for all episodes

_episodes/01-query.md, _episodes/02-coords.md, _episodes/03-motion.md
- remove duplicate table output
- move "notes" to callout chunks
- separate out code and explanations in exercise solutions
=> More formatting fixes

_episodes/01-query.md, _episodes/02-coords.md, _episodes/03-motion.md, _episodes/04-select.md, _episodes/05-join.md, _episodes/06-photo.md, _episodes/07-plot.md
For all 7 episodes, move the outline section to a "checklist" callout box. Also remove the duplicate learning objectives.
=> move outline to checklist callout box

_episodes/02-coords.md, bin/lesson_check.py
- Render broken symbols. 
- Change exercise hint
=> general episode cleanup

_episodes/03-motion.md
- scatterplot --> scatter plot
- GD1Koposov10 --> GD1
- incorporate other wording suggestions from @abostroem
=> incorporate language suggestions

_episodes/03-motion.md, _extras/prereqs.md, index.md
Sorry @rudyphd - I'm not sure why the old commits that have already been merged are showing up in the commit history here. Next time I'll make a clean branch. 
The changes to review for this PR are to the index.md and extras/prereqs.md files. I'm copying over prereqs from the [Image Processing lesson](https://github.com/datacarpentry/image-processing/blob/gh-pages/_extras/prereqs.md) to get us started. I'm sure there are some differences in specific functions and packages we want people to be familiar with. Would appreciate modifications to the prereqs from @abostroem or @rudyphd.
=> add prereqs

_episodes/01-query.md, _episodes/02-coords.md
Will be adding alt text for other images later, but may not finish in time for our all hands. You can either review and merge this one now or wait until I've gone through all of the episodes, whichever you prefer. @rudyphd
=> Alt text for images in first 2 episodes

_episodes/03-motion.md, _extras/guide.md
These are the single episode changes for lesson 3 that I'd claimed
=> Episode3 azalee updates

_episodes/02-coords.md
Added the results table to the solution for the second exercise and an explanation of why we write functions
=> Episode2 azalee updates

_episodes/02-coords.md, _episodes/03-motion.md, _episodes/04-select.md, _episodes/05-join.md, _extras/guide.md
Updates for Episode 4 (including code changes to 2, 3, and 5). See individual commits for details
=> Episode4 azalee updates

index.md
@abostroem - would really appreciate your take on this. I've left a couple of callouts for you to add more detail where I don't have the required background knowledge.
=> add rough intro text to homepage

_episodes/03-motion.md, _episodes/04-select.md, _episodes/05-join.md, _episodes/06-photo.md, _episodes/07-plot.md
@abostroem or @rudyphd please check and make sure the interpretations I've added in the alt-text of the graphs is accurate. It should be of the format 
alt= “`Chart type` of `type of data` where `reason for including chart`” as suggested by Amy Cesal in [this article](https://medium.com/nightingale/writing-alt-text-for-data-visualization-2a218ef43f81).
=> Add alt text for episodes 3-7

_episodes/06-photo.md, _episodes/07-plot.md, _extras/guide.md
Updates to Lesson 6:
* Add explanation of `front_back` function before we write it
* Clarify origin of `contains_points` in instructor notes
* Fix axis labels in last plot
* Update final plot to match function
* Move `plot_second_selection` function to episode 6
* Rename `plot_second_selection` function `plot_cmd_selection`
* Add mathtext explanation 
* Add `plt.title` explanation
=> Azalee episode6 updates

_episodes/07-plot.md, _extras/guide.md
My updates for episode 7 (includes all but one of the unclaimed ones):
* Updates matplotlib urls to stable rather than a specific version
* Removed Latex section and added usetex error to episode 6 instructor notes
* Removed plot_cmd function and added import plot_cmd placeholder (this is already defined in episode 6)
* Modified language in Polygon exercise so that it adds text after plot_cmd function consistent with what is shown below (and so we don't have to modify plot_cmd)
* Added solution to tight_layout exercise
=> Azalee chapter7 updates

_episodes/02-coords.md, _episodes/03-motion.md, _episodes/04-select.md
<details>
<summary><strong>Instructions</strong></summary>
Thanks for contributing! :heart:
If this contribution is for instructor training, please email the link to this contribution to
checkout@carpentries.org so we can record your progress. You've completed your contribution
step for instructor checkout by submitting this contribution!
Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution. Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, please contact The Carpentries Team at team@carpentries.org.
You may …
=> Updates to Episode 3 from Final Edits Doc

_episodes/01-query.md, _episodes/02-coords.md, _episodes/03-motion.md, _episodes/04-select.md, _episodes/05-join.md, _episodes/06-photo.md, _episodes/07-plot.md, index.md
- Removes contractions for compatibility with screen readers
- Removes some potentially demotivating and/or ableist language
- Fixes some broken formatting
- Removes references to "notebook" and "chunk" left over from when lesson files were Jupyter notebooks
=> Formatting and demotivating language check

_episodes/03-motion.md
Based on feedback https://github.com/datacarpentry/astronomy-python/commit/9b7950b795337ee4d9961b286a4f059f2033a3b5#commitcomment-51355228
=> Change name of frame back to GD-1

_episodes/03-motion.md, _episodes/05-join.md, _episodes/06-photo.md
In running the code to make the data files I caught one typo and two places were we used duplicate variable names. This PR fixes those three issues
=> Fixing typos

_episodes/03-motion.md, _episodes/04-select.md, _episodes/05-join.md, _episodes/06-photo.md, _episodes/07-plot.md
As discussed at our last monthly meeting, makes the section with instructions on how to set up your environment to start from the current episode collapsable. These sections will not show by default, but can be toggled by the user as desired.
=> Make "starting from this episode" collapsable

_episodes/04-select.md
This adds the gd1_frame definition to the starting from here previously defined quantities section addressing issue #71
=> adding gd1_frame definition to lesson 4

_episodes/02-coords.md
=> Fix paper URL in episode 2

_episodes/03-motion.md
Changes results --> polygon_results and adds a little clarification about what Table we're talking about
=> missed a variable name change in pandas fix

_episodes/03-motion.md
=> catching one more variable change (results --> polygon_results)

_episodes/05-join.md
As noticed by @ErinBecker during the pilot workshop.
=> fix formatting of discussion box

_extras/calculating_MIST_isochrone.md
=> adding title to file that describes making the isochrone

_episodes/02-coords.md, _episodes/04-motion.md, _episodes/05-select.md, _episodes/06-join.md, _episodes/07-photo.md, _episodes/08-plot.md
Fixes https://github.com/datacarpentry/astronomy-python/issues/42
=> Make paths relative

setup.md
Fixes https://github.com/datacarpentry/astronomy-python/issues/67, follows approach from https://datacarpentry.org/OpenRefine-ecology-lesson/00-getting-started/index.html
=> Move data download to desktop

_episodes/06-join.md
addresses comment in issue #107
=> adding callout for british spelling of neighbors

_episodes/07-photo.md, student_download/episode_functions.py
While this was an example of reusing code - it was a weak one that wasn't reused later in the lesson. To save time and make the reversing of the array more clear, I removed the function. I've check that it doesn't reoccur in other episodes or the instructor guide.
=> removed one more reference to function

_episodes/07-photo.md
addresses photometry issue listed in #107
=> adding more context to polygon contains_points exercise

CITATION, README.md
- add Zenodo DOI badge to README
- add citation to CITATION
=> Add publication info

_episodes/03-transform.md, _episodes/04-motion.md, _episodes/05-select.md, _episodes/06-join.md, _episodes/07-photo.md, _episodes/08-plot.md
Fixes https://github.com/datacarpentry/astronomy-python/issues/122
=> Callout to prereq

_episodes/07-photo.md
@catherine-martlin PR made me realize that we need alt text in the last figure. Updating to duplicate previous figure.
=> adding alt-text to final figure

.github/workflows/website.yml, _episodes/01-query.md, _episodes/02-coords.md, _episodes/04-motion.md, _episodes/06-join.md, _episodes/07-photo.md
These are just a series of small updates to have the output numbers from queries and file size checks match what currently shows up when run in the notebook.
=> Updates before workshop

_episodes/01-query.md, _episodes/02-coords.md
adding parallax to query and result summary of polygon_job (episode 2), resolving issue #156
=> Fix issue156

_episodes/08-plot.md
=> making plt.annotate in code font

_episodes/01-query.md, _extras/link-list.md
Updated the link to close issue #189
=> Issue189 - Extra Link to MEF information

index.md
Removes unnecessary comments - the HTML one, which does render as a comment and the liquid one, which does not (it displays on the page).
=> Remove unnecessary comments

episodes/06-join.md
=> fixing second join statement to reference correct tables

episodes/06-join.md
=> adding clarifying limitations of CSV file format

CONTRIBUTING.md
Closes #204 
Fixes two urls as described in issued 204 [how-contribute] and [repo]
=> Issue204 contributing

episodes/08-plot.md
Closes #201 
Typo error has been resolved.
=> axis changed to axes
